### ISSUE TITLE
Still Being Developed

### ISSUE THREAD

**Issue by joshua1** [nirvana/couchie#16]
Hi Am New to Elixir and we are currently porting an application to elixir with a couchbase DB. I wish to know if this is still being developed and if this can be extended to work with Ecto.
Thanks

**Comment by n1rvana** [comment]
Hello. Yes, this is still being developed. We should have a major update to this released soon.    I don't think couchbase makes sense with ecto given the way I think ecto works, but I can't be certain.  Please watch the repo, and you'll get updates soon.

**Comment by n1rvana** [comment]
Couchie is mostly complete.  It can be extended if you want.  Not sure it makes sense to work with Ecto or not... but it is working, and is being used in production now.

**Comment by greentornado** [comment]
Can someone port to ecto :D or point out a way to convert to an ector adapter 
Thanks

**Comment by n1rvana** [comment]
I'd be willing to look into that.  Previously I did look at ecto as an adapter but didn't find any good docs for it.

**Comment by greentornado** [comment]
Maybe you can look at current Ecto docs
https://hexdocs.pm/ecto/Ecto.html

**Comment by n1rvana** [comment]
Looks like it should be possible, just create ecto wrappers around couchie.  Do that, and give me some simple test/repro-steps and I'll be happy to test it and take a pull request.

**Comment by n1rvana** [comment]
Closed pending a PR or further questions.
